version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/web.dockerfile
    container_name: my-personal-portfolio-web

    ports:
        - 8082:80

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    links:
      - db

  db:
    image: mysql:5.7
    container_name: my-personal-portfolio-db

    ports:
      - 3306:3306

    volumes:
      - /home/computer/Work/projects/personal_databases/.mysql/my-personal-portfolio-rest:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: computer@1.6
